export default function TermsPage() {
  const h1: React.CSSProperties = { fontFamily: 'var(--font-serif), Georgia, serif', fontSize: 36, fontWeight: 700, marginBottom: 8 }
  const h2: React.CSSProperties = { fontFamily: 'var(--font-serif), Georgia, serif', fontSize: 22, fontWeight: 700, marginBottom: 12, marginTop: 48 }
  const p: React.CSSProperties = { fontSize: 16, marginBottom: 16 }
  const ul: React.CSSProperties = { fontSize: 16, marginBottom: 16, paddingLeft: 24, lineHeight: 1.9 }

  return (
    <main style={{ maxWidth: 680, margin: '0 auto', padding: '80px 24px 120px', fontFamily: 'var(--font-sans), sans-serif', color: '#2C3528', lineHeight: 1.75 }}>
      <h1 style={h1}>Terms of Service</h1>
      <p style={{ fontSize: 14, color: '#6B7566', marginBottom: 48 }}>Last updated: May 2026</p>

      <p style={p}>
        These Terms of Service govern your use of Bookwise, a product of The Zen Bookkeeper LLC. By creating an account or using the service, you agree to these terms. If you do not agree, do not use Bookwise.
      </p>

      <h2 style={h2}>Eligibility</h2>
      <p style={p}>
        You must be at least 18 years old to use Bookwise. By using the service, you represent that you meet this requirement. You must also have the legal authority to enter into a binding agreement.
      </p>

      <h2 style={h2}>What Bookwise Is</h2>
      <p style={p}>
        Bookwise is a financial organization tool designed for independent wellness practitioners, including coaches, personal trainers, and bodyworkers. It helps you track income and expenses, visualize how your money is allocated across spending categories, and prepare data for review with a licensed CPA.
      </p>
      <p style={p}>
        Bookwise does not provide financial advice, tax advice, investment advice, or legal advice. Nothing in the app or generated by Sage AI should be interpreted as a directive or a recommendation to take any financial or legal action.
      </p>

      <h2 style={h2}>Your Account</h2>
      <p style={p}>
        You are responsible for maintaining the security of your account credentials. You are responsible for all activity that occurs under your account. Notify us immediately at hello@thezenbookkeeper.com if you believe your account has been compromised.
      </p>
      <p style={p}>
        You may not share your account with others or use the account of another person without permission.
      </p>

      <h2 style={h2}>Your Responsibilities</h2>
      <p style={p}>You are responsible for:</p>
      <ul style={ul}>
        <li>The accuracy of information you enter into Bookwise</li>
        <li>Reviewing all financial data with a licensed CPA before making tax or financial decisions</li>
        <li>Complying with all applicable laws in your use of the service</li>
        <li>Not using Bookwise for any unlawful purpose</li>
        <li>Not attempting to reverse engineer, copy, or redistribute any part of the service</li>
      </ul>

      <h2 style={h2}>Sage AI Observations</h2>
      <p style={p}>
        Bookwise includes Sage AI, a feature that observes patterns in your financial data and shares what it notices. Sage AI is powered by Anthropic's Claude AI model.
      </p>
      <p style={p}>
        Sage AI does not give financial advice, tax advice, or legal advice. Its outputs are observations only. Nothing Sage AI says should be treated as a directive or a guarantee. Always work with a licensed CPA before filing your taxes or making significant financial decisions.
      </p>

      <h2 style={h2}>Bank Account Connections (Plaid)</h2>
      <p style={p}>
        Bookwise uses Plaid Technologies, Inc. to enable you to connect your bank accounts. By connecting a bank account, you authorize Plaid to access your financial institution on your behalf and share your account and transaction data with Bookwise.
      </p>
      <p style={p}>
        You may disconnect your bank account at any time from your Settings page. Disconnecting removes Bookwise's access to your account going forward. Previously imported transactions will remain in your ledger unless you delete them manually.
      </p>
      <p style={p}>
        Your use of Plaid is also subject to <a href="https://plaid.com/en/legal/account-terms/" style={{ color: '#7C9A7E' }}>Plaid's End User Services Agreement</a>.
      </p>

      <h2 style={h2}>Your Data</h2>
      <p style={p}>
        You own your financial data. Bookwise does not claim ownership of any data you enter or import. You can export your data at any time from the Reports page and delete your account at any time from your Settings page.
      </p>
      <p style={p}>
        By using Bookwise, you grant us a limited license to store and process your data for the purpose of providing the service.
      </p>

      <h2 style={h2}>Acceptable Use</h2>
      <p style={p}>You agree not to:</p>
      <ul style={ul}>
        <li>Use Bookwise to engage in fraud, money laundering, or any illegal activity</li>
        <li>Attempt to gain unauthorized access to any part of the service or its infrastructure</li>
        <li>Scrape, copy, or reproduce any part of the service without written permission</li>
        <li>Interfere with or disrupt the service or servers connected to it</li>
        <li>Use the service in a way that could harm other users or The Zen Bookkeeper LLC</li>
      </ul>

      <h2 style={h2}>Intellectual Property</h2>
      <p style={p}>
        All content, design, code, and features of Bookwise are the property of The Zen Bookkeeper LLC or its licensors. The Bookwise name, logo, and Sage AI are proprietary. You may not use them without written permission.
      </p>

      <h2 style={h2}>Limitation of Liability</h2>
      <p style={p}>
        Bookwise is provided "as is" without warranties of any kind. To the fullest extent permitted by law, The Zen Bookkeeper LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service.
      </p>
      <p style={p}>
        We do not guarantee the accuracy of AI-generated insights, tax estimates, or category assignments. The 25% tax set-aside rate displayed in the app is a commonly used planning guideline. Your actual tax liability depends on your specific situation and must be confirmed with a licensed CPA.
      </p>
      <p style={p}>
        Our total liability to you for any claim arising out of your use of Bookwise shall not exceed the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2 style={h2}>Account Termination</h2>
      <p style={p}>
        You may delete your account at any time from the Settings page. We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or pose a risk to the service or other users.
      </p>
      <p style={p}>
        Upon termination, your data will be deleted within 30 days, except where retention is required by law.
      </p>

      <h2 style={h2}>Governing Law</h2>
      <p style={p}>
        These terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Any dispute arising under these terms shall be resolved in the courts of Dallas County, Texas, and you consent to personal jurisdiction there.
      </p>

      <h2 style={h2}>Changes to These Terms</h2>
      <p style={p}>
        We may update these terms as the product evolves. When we make material changes, we will notify active users by email at least 14 days before the changes take effect. Continued use of Bookwise after that date constitutes acceptance of the updated terms.
      </p>

      <h2 style={h2}>Contact</h2>
      <p style={p}>
        Questions about these terms? Contact us at <a href="mailto:hello@thezenbookkeeper.com" style={{ color: '#7C9A7E' }}>hello@thezenbookkeeper.com</a>.
      </p>
      <p style={p}>
        The Zen Bookkeeper LLC<br />
        Dallas-Fort Worth, Texas
      </p>

      <p style={{ fontSize: 13, color: '#6B7566', marginTop: 64, paddingTop: 24, borderTop: '1px solid #E0D8CF' }}>
        These terms apply to all users of Bookwise, including beta participants.
      </p>
    </main>
  )
}
