export type Industry = 'coach' | 'trainer' | 'bodyworker'

export const IQ_MAPS: Record<Industry, Record<string, string>> = {
  coach: {
    'Income': 'Income',
    'Session Income': 'Coaching Income',
    'Package Income': 'Program Income',
    'Retainer Income': 'Retainer Income',
    'Tip Income': 'Tip',
    'Other Income': 'Other Income',
    'Expenses': 'Business Expenses',
    'Supplies': 'Office Supplies',
    'Equipment': 'Tools and Tech',
    'Software': 'Platforms and Apps',
    'Rent': 'Studio or Office Rent',
    'Facility Fee': 'Coworking Fee',
    'Insurance': 'Liability Coverage',
    'Continuing Education': 'Certifications and Training',
    'Marketing': 'Client Attraction',
    'Mileage': 'Client Travel',
    'Meals': 'Client Meetings',
    'Professional Services': 'Professional Support',
    'Utilities': 'Utilities',
    'Phone': 'Phone',
    'Internet': 'Internet',
    'Other Expense': 'Other Business Cost',
    'Sessions': 'Coaching Sessions',
    'Session': 'Coaching Session',
    'Appointments': 'Sessions',
    'Table Time': 'Coaching Hours',
    'Hours Worked': 'Hours Coached',
    'Profit Bucket': 'Growth Fund',
    'Tax Bucket': 'Taxes Set Aside',
    'Operations Bucket': 'Daily Operations',
    'Take-Home': 'Take-Home',
    'Pay Myself': 'Pay Myself',
    'Profit and Loss': 'Practice Summary',
    'Net Profit': 'Take-Home',
    'Gross Income': 'Total Coaching Income',
    'Total Expenses': 'Total Business Costs',
    'Tax Set-Aside Estimate': 'Taxes Set Aside Estimate',
    'Sessions Given': 'Sessions Coached Today',
    'Miles Driven': 'Miles to Clients',
    'your practice': 'your coaching practice',
    'your clients': 'your clients',
    'Clients': 'Clients',
    'Client': 'Client',
  },
  trainer: {
    'Income': 'Income',
    'Session Income': 'Training Income',
    'Package Income': 'Package Income',
    'Retainer Income': 'Membership Income',
    'Tip Income': 'Tip',
    'Other Income': 'Other Income',
    'Expenses': 'Gym Expenses',
    'Supplies': 'Consumables',
    'Equipment': 'Gym Equipment',
    'Software': 'Fitness Apps',
    'Rent': 'Gym or Studio Fee',
    'Facility Fee': 'Facility Fee',
    'Insurance': 'Liability Coverage',
    'Continuing Education': 'Certifications and CECs',
    'Marketing': 'Client Attraction',
    'Mileage': 'Travel to Sites',
    'Meals': 'Client Meetings',
    'Professional Services': 'Professional Support',
    'Utilities': 'Utilities',
    'Phone': 'Phone',
    'Internet': 'Internet',
    'Other Expense': 'Other Business Cost',
    'Sessions': 'Training Sessions',
    'Session': 'Training Session',
    'Appointments': 'Sessions',
    'Table Time': 'Floor Time',
    'Hours Worked': 'Hours Trained',
    'Profit Bucket': 'Growth Fund',
    'Tax Bucket': 'Taxes Set Aside',
    'Operations Bucket': 'Daily Operations',
    'Take-Home': 'Take-Home',
    'Pay Myself': 'Pay Myself',
    'Profit and Loss': 'Performance Report',
    'Net Profit': 'Take-Home',
    'Gross Income': 'Total Training Income',
    'Total Expenses': 'Total Gym Costs',
    'Tax Set-Aside Estimate': 'Taxes Set Aside Estimate',
    'Sessions Given': 'Sessions Trained Today',
    'Miles Driven': 'Miles Traveled',
    'your practice': 'your training business',
    'your clients': 'your clients',
    'Clients': 'Clients',
    'Client': 'Client',
  },
  bodyworker: {
    'Income': 'Income',
    'Session Income': 'Appointment Income',
    'Package Income': 'Package Income',
    'Retainer Income': 'Membership Income',
    'Tip Income': 'Tip',
    'Other Income': 'Other Income',
    'Expenses': 'Practice Expenses',
    'Supplies': 'Linens and Supplies',
    'Equipment': 'Treatment Supplies',
    'Software': 'Booking Tools',
    'Rent': 'Treatment Room Rent',
    'Facility Fee': 'Suite or Room Fee',
    'Insurance': 'Liability Coverage',
    'Continuing Education': 'CE Credits and Training',
    'Marketing': 'Client Attraction',
    'Mileage': 'Travel to Clients',
    'Meals': 'Client Meetings',
    'Professional Services': 'Professional Support',
    'Utilities': 'Utilities',
    'Phone': 'Phone',
    'Internet': 'Internet',
    'Other Expense': 'Other Practice Cost',
    'Sessions': 'Appointments',
    'Session': 'Appointment',
    'Appointments': 'Appointments',
    'Table Time': 'Table Time',
    'Hours Worked': 'Hours on the Table',
    'Profit Bucket': 'Growth Fund',
    'Tax Bucket': 'Taxes Set Aside',
    'Operations Bucket': 'Daily Operations',
    'Take-Home': 'Take-Home',
    'Pay Myself': 'Pay Myself',
    'Profit and Loss': 'Practice Summary',
    'Net Profit': 'Take-Home',
    'Gross Income': 'Total Appointment Income',
    'Total Expenses': 'Total Practice Costs',
    'Tax Set-Aside Estimate': 'Taxes Set Aside Estimate',
    'Sessions Given': 'Appointments Today',
    'Miles Driven': 'Miles to Clients',
    'your practice': 'your practice',
    'your clients': 'your clients',
    'Clients': 'Clients',
    'Client': 'Client',
  },
}

// Schedule C shadow map - used only in CSV export, never shown in UI
export const SCHEDULE_C_MAP: Record<string, { label: string; line: string }> = {
  'Session Income': { label: 'Gross Receipts or Sales', line: 'Line 1' },
  'Package Income': { label: 'Gross Receipts or Sales', line: 'Line 1' },
  'Retainer Income': { label: 'Gross Receipts or Sales', line: 'Line 1' },
  'Tip Income': { label: 'Other Income', line: 'Line 6' },
  'Other Income': { label: 'Other Income', line: 'Line 6' },
  'Supplies': { label: 'Supplies', line: 'Line 22' },
  'Equipment': { label: 'Supplies', line: 'Line 22' },
  'Software': { label: 'Office Expense', line: 'Line 18' },
  'Rent': { label: 'Rent on Business Property', line: 'Line 20b' },
  'Facility Fee': { label: 'Rent on Business Property', line: 'Line 20b' },
  'Insurance': { label: 'Insurance', line: 'Line 15' },
  'Continuing Education': { label: 'Other Expense', line: 'Line 27a' },
  'Marketing': { label: 'Advertising', line: 'Line 8' },
  'Mileage': { label: 'Car and Truck Expenses', line: 'Line 9' },
  'Meals': { label: 'Meals (50% deductible)', line: 'Line 24b' },
  'Professional Services': { label: 'Legal and Professional', line: 'Line 17' },
  'Utilities': { label: 'Utilities', line: 'Line 26' },
  'Phone': { label: 'Utilities', line: 'Line 26' },
  'Internet': { label: 'Utilities', line: 'Line 26' },
  'Other Expense': { label: 'Other Expense', line: 'Line 27a' },
}
